# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autoConfigMainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(713, 298)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(713, 298))
        MainWindow.setMaximumSize(QtCore.QSize(713, 298))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 10, 693, 211))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_3.addWidget(self.label_6)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.step1Icon = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step1Icon.sizePolicy().hasHeightForWidth())
        self.step1Icon.setSizePolicy(sizePolicy)
        self.step1Icon.setText(_fromUtf8(""))
        self.step1Icon.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/blank.png")))
        self.step1Icon.setAlignment(QtCore.Qt.AlignCenter)
        self.step1Icon.setObjectName(_fromUtf8("step1Icon"))
        self.horizontalLayout.addWidget(self.step1Icon)
        self.step1Text = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step1Text.sizePolicy().hasHeightForWidth())
        self.step1Text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.step1Text.setFont(font)
        self.step1Text.setObjectName(_fromUtf8("step1Text"))
        self.horizontalLayout.addWidget(self.step1Text)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.step2Icon = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step2Icon.sizePolicy().hasHeightForWidth())
        self.step2Icon.setSizePolicy(sizePolicy)
        self.step2Icon.setText(_fromUtf8(""))
        self.step2Icon.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icomoon-cancel-circle_32_0_bd3939_none.png")))
        self.step2Icon.setAlignment(QtCore.Qt.AlignCenter)
        self.step2Icon.setObjectName(_fromUtf8("step2Icon"))
        self.horizontalLayout_2.addWidget(self.step2Icon)
        self.step2Text = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step2Text.sizePolicy().hasHeightForWidth())
        self.step2Text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.step2Text.setFont(font)
        self.step2Text.setObjectName(_fromUtf8("step2Text"))
        self.horizontalLayout_2.addWidget(self.step2Text)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.step3Icon = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step3Icon.sizePolicy().hasHeightForWidth())
        self.step3Icon.setSizePolicy(sizePolicy)
        self.step3Icon.setText(_fromUtf8(""))
        self.step3Icon.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icomoon-cancel-circle_32_0_bd3939_none.png")))
        self.step3Icon.setAlignment(QtCore.Qt.AlignCenter)
        self.step3Icon.setObjectName(_fromUtf8("step3Icon"))
        self.horizontalLayout_3.addWidget(self.step3Icon)
        self.step3Text = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step3Text.sizePolicy().hasHeightForWidth())
        self.step3Text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.step3Text.setFont(font)
        self.step3Text.setObjectName(_fromUtf8("step3Text"))
        self.horizontalLayout_3.addWidget(self.step3Text)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.step4Icon = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step4Icon.sizePolicy().hasHeightForWidth())
        self.step4Icon.setSizePolicy(sizePolicy)
        self.step4Icon.setText(_fromUtf8(""))
        self.step4Icon.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icomoon-cancel-circle_32_0_bd3939_none.png")))
        self.step4Icon.setAlignment(QtCore.Qt.AlignCenter)
        self.step4Icon.setObjectName(_fromUtf8("step4Icon"))
        self.horizontalLayout_4.addWidget(self.step4Icon)
        self.step4Text = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step4Text.sizePolicy().hasHeightForWidth())
        self.step4Text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.step4Text.setFont(font)
        self.step4Text.setObjectName(_fromUtf8("step4Text"))
        self.horizontalLayout_4.addWidget(self.step4Text)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.step5Icon = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step5Icon.sizePolicy().hasHeightForWidth())
        self.step5Icon.setSizePolicy(sizePolicy)
        self.step5Icon.setText(_fromUtf8(""))
        self.step5Icon.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icomoon-cancel-circle_32_0_bd3939_none.png")))
        self.step5Icon.setAlignment(QtCore.Qt.AlignCenter)
        self.step5Icon.setObjectName(_fromUtf8("step5Icon"))
        self.horizontalLayout_6.addWidget(self.step5Icon)
        self.step5Text = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step5Text.sizePolicy().hasHeightForWidth())
        self.step5Text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.step5Text.setFont(font)
        self.step5Text.setObjectName(_fromUtf8("step5Text"))
        self.horizontalLayout_6.addWidget(self.step5Text)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.step6Icon = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step6Icon.sizePolicy().hasHeightForWidth())
        self.step6Icon.setSizePolicy(sizePolicy)
        self.step6Icon.setText(_fromUtf8(""))
        self.step6Icon.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icomoon-cancel-circle_32_0_bd3939_none.png")))
        self.step6Icon.setAlignment(QtCore.Qt.AlignCenter)
        self.step6Icon.setObjectName(_fromUtf8("step6Icon"))
        self.horizontalLayout_5.addWidget(self.step6Icon)
        self.step6Text = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step6Text.sizePolicy().hasHeightForWidth())
        self.step6Text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.step6Text.setFont(font)
        self.step6Text.setObjectName(_fromUtf8("step6Text"))
        self.horizontalLayout_5.addWidget(self.step6Text)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(600, 260, 91, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName(_fromUtf8("label"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_Quit = QtGui.QAction(MainWindow)
        self.action_Quit.setObjectName(_fromUtf8("action_Quit"))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Filimin Auto Configuration", None))
        self.label_6.setText(_translate("MainWindow", "Friendship Lamp Automatic Setup", None))
        self.step1Text.setText(_translate("MainWindow", "Retrieving Wi-Fi Credentials", None))
        self.step2Text.setText(_translate("MainWindow", "Creating Profile", None))
        self.step3Text.setText(_translate("MainWindow", "Connecting to Lamp", None))
        self.step4Text.setText(_translate("MainWindow", "Communicating to Lamp", None))
        self.step5Text.setText(_translate("MainWindow", "Confirming New Settings", None))
        self.step6Text.setText(_translate("MainWindow", "Connecting back to Wi-Fi", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#8c8c8c;\">Version 0.3.0</span></p></body></html>", None))
        self.action_Quit.setText(_translate("MainWindow", "&Quit", None))

import icons_rc
